version: '3'
services:
  php:
    container_name: docktober_php
    build:
      context: ./php-fpm
    volumes:
      - /var/www/html/Website/octobercms:/var/www/html/octobercms

  web:
    container_name: docktober_web
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html/Website/octobercms:/var/www/html/octobercms
    links:
      - php
